server:
  port: 8781
spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/quangyen/spring-cloud-config-file
#          uri: C:/key
#          clone-on-start: true
  security:
    user:
      password: root
      name: root

#encrypt:
#  key-store:
#    location: config-server.jks
#    password: my-s70r3-s3cr3t
#    alias: config-server-key
#    secret: my-k34-s3cr3t
