spring:
  profiles:
    active: instance3
  application:
    name: eureka-server
server:
  port: 8763
eureka:
  instance:
    hostname: instance3
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/