spring:
  profiles:
    active: instance2
  application:
    name: eureka-server
server:
  port: 8762
eureka:
  instance:
    hostname: instance2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8763/eureka/